VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", :ip => "10.2.2.70"

  config.vm.synced_folder "../consul-dns-srv-demo/", "/srv/NGINX-Demos/consul-dns-srv-demo"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./setup_consul_dns_srv_demo.yml"
  end

end
