Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "private_network", :ip => "10.2.2.70"

  config.vm.synced_folder "../consul-dns-srv-demo/", "/srv/NGINX-Demos/consul-dns-srv-demo"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./setup_consul_dns_srv_demo.yml"
    ansible.extra_vars = {
      ansible_python_interpreter:"/usr/bin/python3"
    }
  end

end
