{
 "title": "NGINX Telemetry",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nginx_instance_name",
    "label": "NGINX Instance Name",
    "query": "select distinct display_name from nms.metrics"
   }
  ]
 },
 "panels": [
  {
   "title": "Agent Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "nms",
     "dateColDataType": "partition_key",
     "dateTimeColDataType": "creation_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    message\nFROM $table\n\nWHERE alias = '$nginx_instance_name'\nORDER BY db_timestamp DESC\nLIMIT 1",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(creation_time), 1) * 1) * 1000 as t,\n    message\nFROM nms.events\n\nWHERE alias = 'ubuntu'\nORDER BY db_timestamp DESC\nLIMIT 1",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Agent Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "database": "nms",
     "dateColDataType": "partition_key",
     "dateTimeColDataType": "creation_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    status\nFROM $table\n\nWHERE alias = '$nginx_instance_name'\nORDER BY db_timestamp DESC\nLIMIT 1",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(creation_time), 2) * 2) * 1000 as t,\n    status\nFROM nms.events\n\nWHERE alias = 'ubuntu'\nORDER BY db_timestamp DESC\nLIMIT 1",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Last change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "database": "nms",
     "dateColDataType": "partition_key",
     "dateTimeColDataType": "creation_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    db_timestamp\nFROM $table\n\nWHERE alias = '$nginx_instance_name'\nORDER BY db_timestamp DESC\nLIMIT 1",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(creation_time), 1) * 1) * 1000 as t,\n    db_timestamp\nFROM nms.events\n\nWHERE alias = 'ubuntu'\nORDER BY db_timestamp DESC\nLIMIT 1",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "nginx_instance",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.cpu.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648250847) AND timestamp <= toDateTime(1648254447)\n    and name like 'system.cpu.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.load.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648250842) AND timestamp <= toDateTime(1648254442)\n    and name like 'system.load.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.mem.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248449) AND timestamp <= toDateTime(1648248749)\n    and name like 'system.mem.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.disk.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248464) AND timestamp <= toDateTime(1648248764)\n    and name like 'system.disk.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and (name like 'system.io.iops_%' or name like 'system.io.kbs_%') and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248921) AND timestamp <= toDateTime(1648249221)\n    and (name like 'system.io.iops_%' or name like 'system.io.kbs_%') and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.io.wait_%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 2) * 2) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648250834) AND timestamp <= toDateTime(1648254434)\n    and name like 'system.io.wait_%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.net.bytes_%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248475) AND timestamp <= toDateTime(1648248775)\n    and name like 'system.net.bytes_%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "Network Packet Statistics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.net.packets_%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248486) AND timestamp <= toDateTime(1648248786)\n    and name like 'system.net.packets_%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    }
   ]
  },
  { "title": "SSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "SSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'plus.ssl.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248527) AND timestamp <= toDateTime(1648248827)\n    and name like 'plus.ssl.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  { "title": "HTTP & SSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "nginx_instance" },
  {
   "title": "HTTP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'nginx.http.conn.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248511) AND timestamp <= toDateTime(1648248811)\n    and name like 'nginx.http.conn.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'nginx.http.request.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248516) AND timestamp <= toDateTime(1648248816)\n    and name like 'nginx.http.request.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'plus.http.status.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248532) AND timestamp <= toDateTime(1648248832)\n    and name like 'plus.http.status.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "HTTP Upstreams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream healthchecks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'plus.http.upstream.peers.health_checks.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248592) AND timestamp <= toDateTime(1648248892)\n    and name like 'plus.http.upstream.peers.health_checks.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "HTTP upstream peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'plus.http.upstream.peers.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248598) AND timestamp <= toDateTime(1648248898)\n    and name like 'plus.http.upstream.peers.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "Upstream response status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'plus.http.upstream.peers.status.%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248604) AND timestamp <= toDateTime(1648248904)\n    and name like 'plus.http.upstream.peers.status.%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "HTTP upstream peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and (name like 'plus.http.upstream.peers.request.%' or name like 'plus.http.upstream.peers.response.%') and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248611) AND timestamp <= toDateTime(1648248911)\n    and (name like 'plus.http.upstream.peers.request.%' or name like 'plus.http.upstream.peers.response.%') and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    },
    {
     "title": "HTTP upstream bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "nms",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'plus.http.upstream.peers.bytes_%' and display_name = '$nginx_instance_name'\nGROUP BY name,t\n\nORDER BY name,t\n",
       "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1648248618) AND timestamp <= toDateTime(1648248918)\n    and name like 'plus.http.upstream.peers.bytes_%' and display_name = 'devel'\nGROUP BY name,t\n\nORDER BY name,t",
       "round": "0s",
       "table": "metrics"
      }
     ]
    }
   ]
  }
 ]
}