VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", :ip => "10.2.2.70"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../ansible/setup_consul_demo.yml"
  end
end
